image: php:7.2.15

pipelines:
    default:
        -   step:
                name: Unit tests
                caches:
                    - composer
                script:
                    - apt-get update && apt-get install -y unzip
                    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
                    - composer install
                    - vendor/bin/phpunit -c tests/phpunit.xml tests/

    branches:
        master:
            - step:
                  name: Deploy
                  script:
                      - echo "This script runs only on commit to the master branch."

            - step:
                  name: Sentry release notification
                  script:
                      -   pipe: sentryio/sentry-new-release:0.1.1
                          variables:
                              SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN
                              SENTRY_ORG: 'starkeen'
                              SENTRY_PROJECT: 'culttourismru'
                              DEBUG: 'true'

            - step:
                  name: Sentry code report
                  script:
                      -   pipe: sentryio/sentry-code-report:0.0.6
                          variables:
                              SENTRY_ORG: 'starkeen'
                              SENTRY_PROJECT_ID: 114324
