version: '3'

services:
    app:
        build:
            ./docker/php
        ports:
            - 80:80
        volumes:
            - ./public:/var/www/html:z
            - ./var/logs/httpd:/var/log/httpd:z
            - ./var/logs/php:/var/log/php
            - ./docker/php/httpd.conf:/usr/local/apache2/conf/httpd.conf:z
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        environment:
            DIRECTORY_ROOT: ${DIRECTORY_ROOT}
        depends_on:
            - mariadb

    mariadb:
        build:
            ./docker/mariadb
        volumes:
            - ./docker/mariadb/data:/var/lib/mysql:z
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3306:3306
