version: '3'

services:
    apache:
        image: httpd:2.4
        volumes:
            - ./:/var/www/html:z
            - ./docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:z
        depends_on:
            - php

    nginx:
        image: nginx:1.13
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - apache

    php:
        build:
            ./docker/php
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mariadb

    mariadb:
        build:
            ./docker/mariadb
        volumes:
            - ./docker/mariadb/data:/var/lib/mysql:z
        environment:
            MYSQL_ROOT_PASSWORD: qwerty
            MYSQL_DATABASE: 'cult'
            MYSQL_USER: 'cult_user'
            MYSQL_PASSWORD: 'cult_password'
        ports:
            - 3306:3306
